sudo: required
language: generic
services:
  - docker
before_install:
  - docker pull autowp/image-host
  - docker exec -it autowp_imagehost_test_web bash -c "./wait-for-it.sh autowp_imagehost_test_mysql:3306"
  - docker exec -it autowp_imagehost_test_mysql bash -c "mysql -uroot -ppassword -e 'create database image_host default character set utf8;'"
  - docker exec -i autowp_imagehost_test_mysql bash -c "mysql -uroot -ppassword image_host" < module/Application/test/_files/dump.sql
  - docker-compose -f test/_files/docker-compose.yml up -d
  - ./wait-for-it.sh localhost:80
  - composer install
  
script:
  - composer cs-check
  - composer phpmd
  - php vendor/bin/phpunit --coverage-clover ./clover.xml

after_success:
  - docker exec -it autowp_imagehost_test_web bash -c "./vendor/bin/coveralls -v"
  - docker exec -it autowp_imagehost_test_web bash -c "./vendor/bin/test-reporter -v --coverage-report=./clover.xml"
  