sudo: required
language: generic
services:
  - docker
addons:
  apt:
    packages:
    - realpath
before_install:
  - sudo /etc/init.d/mysql stop
  - sleep 10
  - docker pull autowp/image-host
  - docker-compose -f test/_files/docker-compose.yml up -d
  - ./wait-for-it.sh localhost:80
  - ./wait-for-it.sh localhost:3306
  - composer install
  
script:
  - composer cs-check
  - composer phpmd
  - php vendor/bin/phpunit --coverage-clover ./clover.xml

after_success:
  - docker exec -it autowp_imagehost_test_web bash -c "./vendor/bin/coveralls -v"
  - docker exec -it autowp_imagehost_test_web bash -c "./vendor/bin/test-reporter -v --coverage-report=./clover.xml"
  